# Generated by Django 3.1.4 on 2020-12-11 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='category title in English')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='category title in Russian')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title of post in English')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='title of post in Russian')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(verbose_name='post body in English')),
                ('body_ru', models.TextField(blank=True, verbose_name='post body in Russian')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='post author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.category', verbose_name='post category')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ('pub_date',),
            },
        ),
    ]
