# Generated by Django 3.1.4 on 2020-12-11 20:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='post body in English'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_ru',
            field=tinymce.models.HTMLField(blank=True, verbose_name='post body in Russian'),
        ),
    ]
